##### add your name and student ID
##### Name: 陳品蓁
##### ID:111524019



# Why numpy & pandas ?
### Fast, flexible, and expressive
- an efficient multi-dimensional container of generic data
### Python is increasingly being used as a scientific language. 
- Matrix and vector manipulations are extremely important for scientific computations. 
- Both NumPy and Pandas have emerged to be essential libraries for any scientific computation,


In [1]:
!wget -r -nd -np -nH -A "ipynb","csv","xlsx" -P "./Week06" --trust-server-names --no-check-certificate "http://ncugo.com/python_edm_2022/week06/"

--2022-10-19 01:10:57--  http://ncugo.com/python_edm_2022/week06/
Resolving ncugo.com (ncugo.com)... 198.55.121.47
Connecting to ncugo.com (ncugo.com)|198.55.121.47|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1709 (1.7K) [text/html]
Saving to: ‘./Week06/index.html.tmp’

index.html.tmp      100%[===================>]   1.67K  --.-KB/s    in 0s      

2022-10-19 01:10:57 (102 MB/s) - ‘./Week06/index.html.tmp’ saved [1709/1709]

Loading robots.txt; please ignore errors.
--2022-10-19 01:10:57--  http://ncugo.com/robots.txt
Reusing existing connection to ncugo.com:80.
HTTP request sent, awaiting response... 404 Not Found
2022-10-19 01:10:57 ERROR 404: Not Found.

Removing ./Week06/index.html.tmp since it should be rejected.

--2022-10-19 01:10:57--  http://ncugo.com/python_edm_2022/week06/?C=N;O=D
Reusing existing connection to ncugo.com:80.
HTTP request sent, awaiting response... 200 OK
Length: 1709 (1.7K) [text/html]
Saving to: ‘./Week06/index.html?C=N;O=D.tmp

##### An Example:

In [3]:
# Creat two lists with fiev students' height and weight 
# What is BMI for the five students?
Height = [159,180,166,178,177]
Weight = [60,80,70,68,70]
BMI=[]
for i in range(5):
    BMI.append(Weight[i]/(Height[i]/100)**2)


In [4]:
BMI

[23.73323840037973,
 24.691358024691358,
 25.402816083611555,
 21.461936624163616,
 22.34351559258195]

In [9]:
import numpy as np
Height = [159,180,166,178,177]
Weight = [60,80,70,68,70]
H=np.array(Height)
W=np.array(Weight)
np.around(W/(H/100)**2,2)

array([23.73, 24.69, 25.4 , 21.46, 22.34])

### Numpy 
##### NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. NumPy is the fundamental package for scientific computing with Python

[連結](https://docs.scipy.org/doc/numpy/reference/routines.html)

In [ ]:
# Array 之中的每一個元素都必須是相同型態
# NumPy is used to work with arrays with the same datatype elements.


In [11]:
import numpy as np 
# 使用numpy 採用np簡寫
# NumPy package can be referred to as np instead of numpy.

array1 = np.array([1,2,3])  #一維的array One Dimension Arrays
array2 = np.array([[1,2,3],
                   [4,5,6]])  #二維的array Two Dimension Arrays

print(array2)
print('維度Number of Dimensions:',array2.ndim) 
print('行列Shape of arrays:',array2.shape) 
print('個數Number of items in arrays:',array2.size) 
print(len(array2))

[[1 2 3]
 [4 5 6]]
維度Number of Dimensions: 2
行列Shape of arrays: (2, 3)
個數Number of items in arrays: 6
2


In [13]:
#One Dimension Arrays
import numpy as np
a = np.array([3,6,9,12,15,18])
b = np.arange(6)  #0-5 int
c = np.zeros(6)  #0 float
d = np.ones(6, dtype = np.int)  
e = np.random.random(6) #float 0-1
f = b-a

print(a,b,c,d,e,f, sep="\n")
print(f<-9)
print(f==-9)

[ 3  6  9 12 15 18]
[0 1 2 3 4 5]
[0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1]
[0.20573132 0.03460113 0.96896787 0.53713218 0.40904553 0.22172473]
[ -3  -5  -7  -9 -11 -13]
[False False False False  True  True]
[False False False  True False False]


In [18]:
#關係運算式=>True/False
print(f)
print(f<-9)
#(1) sum the result
print((f<-9).sum())
#(2) filter condition
print(f[f<-9])


[ -3  -5  -7  -9 -11 -13]
[False False False False  True  True]
2
[-11 -13]


In [21]:
#Two Dimension Arrays
import numpy as np
a=np.array([[3,6,9],
            [12,15,18]])
b=np.arange(6).reshape(2,3) 
c = np.zeros((2,3)) 
d = np.ones((2,3) , dtype = np.int) 
e = np.random.random((2,3)) 

print(a,b,c,d,e, sep="\n")
print(np.sum(a))
print(np.sum(a, axis=1))
print(np.sum(a, axis=0))

[[ 3  6  9]
 [12 15 18]]
[[0 1 2]
 [3 4 5]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[0.66291435 0.16378348 0.01391528]
 [0.18294404 0.25197793 0.15948801]]
63
[18 45]
[15 21 27]


In [22]:
# Opearation of Array加減乘除

import numpy as np
A=np.array([[2,4,6],[8,10,12]])
B=np.arange(6).reshape((2,3)) 

print(A)
print(B)

[[ 2  4  6]
 [ 8 10 12]]
[[0 1 2]
 [3 4 5]]


In [24]:
A+B
A-B


array([[2, 3, 4],
       [5, 6, 7]])

In [25]:
# array join 合併
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
         
print(np.vstack((A,B))) #vertical
print(np.hstack((A,B))) #horizontal


[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [27]:
# array split 分割
import numpy as np
a = np.arange(12).reshape((3,4))
print(a)
print(np.vsplit(a,3)) #vertical up-down
print(np.hsplit(a,2)) #horizontal left-right

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


##### ex: N-dimensional array

In [30]:
# creat a 2-d array with height and weight for the five studetnsnp_2d[0]
Height = [159,180,166,178,177]
Weight = [60,80,70,68,70]
np_2d = np.array([Height,
                  Weight])
np_2d

array([[159, 180, 166, 178, 177],
       [ 60,  80,  70,  68,  70]])

In [35]:
# NumPy Array Indexing
# how to select ?
print(np_2d)
# All students' height
print(np_2d[0])
# All students' weight
print(np_2d[1])
# First and Second students' weight
print(np_2d[1][:2])
print(np_2d[1,:2]) #[row列,columns欄]
# Last three students's hight and weight
print(np_2d[:,-3:])

[[159 180 166 178 177]
 [ 60  80  70  68  70]]
[159 180 166 178 177]
[60 80 70 68 70]
[60 80]
[60 80]
[[166 178 177]
 [ 70  68  70]]


In [38]:
# Basic Statistics

# mean
np.mean(np_2d[1])

# median
np.median(np_2d[1])

# correlation
np.corrcoef(np_2d[0],np_2d[1])

array([[1.        , 0.76462126],
       [0.76462126, 1.        ]])

In [40]:
# Searching Arrays
# You can search an array for a certain value, 
# and return the indexes that get a match.

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr[arr%2 == 1]

array([1, 3, 5, 7])

In [41]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])#01234567位置
x = np.where(arr%2 == 1) 
x

(array([0, 2, 4, 6]),)

### Pandas
##### Pandas建構於Numpy上，Python做資料分析常⽤的套件
- Numpy 是array形式的，沒有欄位名稱或標籤
- Pandas 基於Numpy構建的，有列表的標籤。

- pandas is an open source, providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language. 
- Pandas' data analysis and modeling features enable users to carry out their entire data analysis workflow in Python.

##### Series

In [42]:
# Series是有index的一維array
# Creating a Series by passing a list of values, letting pandas create a default integer index.

import pandas as pd
import numpy as np

# 建立一個 Series 有整數、字串、NAN、浮點數、布林
# Creating a Series with integer, string, NAN, float, bool
s = pd.Series([888,"NCU",np.nan,3.14,True])

print(s)
# 如果是numpy的array呢?
# how about array?

0     888
1     NCU
2     NaN
3    3.14
4    True
dtype: object


In [43]:
s[1]

'NCU'

##### DataFrame

In [52]:
# Create a DataFrame using a NumPy array
df = pd.DataFrame(np.random.randn(7,3))
print(df)
display(df)

          0         1         2
0 -0.178789 -2.248773  1.088373
1 -0.708099  0.790282  0.693067
2  0.265418 -0.617664  0.143759
3 -2.376416  0.403096  0.384039
4 -1.804673  1.348888 -3.564028
5  1.901891 -0.234325  1.222840
6 -1.317345  0.045499 -1.769711


0         1         2
0 -0.178789 -2.248773  1.088373
1 -0.708099  0.790282  0.693067
2  0.265418 -0.617664  0.143759
3 -2.376416  0.403096  0.384039
4 -1.804673  1.348888 -3.564028
5  1.901891 -0.234325  1.222840
6 -1.317345  0.045499 -1.769711

In [51]:
# Create a DataFrame using a NumPy array, with a datetime index
eat = np.random.randint(10,size=(7,3))*5+50
dates = pd.date_range('20170812',periods=7)
df0 = pd.DataFrame(eat)
#加上欄位 with columns amd index
df1 = pd.DataFrame(eat, index=dates, columns=['Break','Lunch','Dinner'])
print(df1)

            Break  Lunch  Dinner
2017-08-12     60     85      80
2017-08-13     60     75      85
2017-08-14     90     65      85
2017-08-15     90     80      60
2017-08-16     85     80      95
2017-08-17     85     95      85
2017-08-18     85     70      65


In [54]:
df1.idxmax(axis=1)

2017-08-12     Lunch
2017-08-13    Dinner
2017-08-14     Break
2017-08-15     Break
2017-08-16    Dinner
2017-08-17     Lunch
2017-08-18     Break
Freq: D, dtype: object

In [55]:
# Create a DataFrame using a dictionary
df2 = pd.DataFrame({'小數float' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    '整數intger' : np.array([3] * 4,dtype='int32'),
                    '時間time' : pd.Timestamp('20170812'),
                    '類別資料category' : pd.Categorical(["test","train","test","train"]),                     
                   }) 
#字典的key代表甚麼? What is the key for
print(df2)

   小數float  整數intger     時間time 類別資料category
0      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
2      1.0         3 2017-08-12         test
3      1.0         3 2017-08-12        train


In [56]:
df2

小數float  整數intger     時間time 類別資料category
0      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
2      1.0         3 2017-08-12         test
3      1.0         3 2017-08-12        train

In [57]:
#DataFrame的屬性
print(df2)
print(df2.dtypes)
print(df2.index) #print(df2.columns), print(df2.values)
print(df2.describe()) #有甚麼要注意的呢? Notice that...

print(df2.T)
print(df2.sort_index(axis=1, ascending=False))
print(df2.sort_values(by='類別資料category'))


   小數float  整數intger     時間time 類別資料category
0      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
2      1.0         3 2017-08-12         test
3      1.0         3 2017-08-12        train
小數float                float32
整數intger                 int32
時間time          datetime64[ns]
類別資料category          category
dtype: object
Int64Index([0, 1, 2, 3], dtype='int64')
       小數float  整數intger
count      4.0       4.0
mean       1.0       3.0
std        0.0       0.0
min        1.0       3.0
25%        1.0       3.0
50%        1.0       3.0
75%        1.0       3.0
max        1.0       3.0
                                0                    1                    2  \
小數float                         1                    1                    1   
整數intger                        3                    3                    3   
時間time        2017-08-12 00:00:00  2017-08-12 00:00:00  2017-08-12 00:00:00   
類別資料category                 test                train  

In [58]:
df2

小數float  整數intger     時間time 類別資料category
0      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
2      1.0         3 2017-08-12         test
3      1.0         3 2017-08-12        train

In [59]:
print(df2.dtypes)

小數float                float32
整數intger                 int32
時間time          datetime64[ns]
類別資料category          category
dtype: object


In [60]:
print(df2.index) #print(df2.columns), print(df2.values)

Int64Index([0, 1, 2, 3], dtype='int64')


In [61]:
print(df2.describe()) #有甚麼要注意的呢? Notice that...

       小數float  整數intger
count      4.0       4.0
mean       1.0       3.0
std        0.0       0.0
min        1.0       3.0
25%        1.0       3.0
50%        1.0       3.0
75%        1.0       3.0
max        1.0       3.0


In [62]:
df2.T# 轉置

0                    1                    2  \
小數float                         1                    1                    1   
整數intger                        3                    3                    3   
時間time        2017-08-12 00:00:00  2017-08-12 00:00:00  2017-08-12 00:00:00   
類別資料category                 test                train                 test   

                                3  
小數float                         1  
整數intger                        3  
時間time        2017-08-12 00:00:00  
類別資料category                train

In [63]:
df2.sort_index(axis=0, ascending=False)

小數float  整數intger     時間time 類別資料category
3      1.0         3 2017-08-12        train
2      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
0      1.0         3 2017-08-12         test

In [64]:
df2.sort_values(by='類別資料category')

小數float  整數intger     時間time 類別資料category
0      1.0         3 2017-08-12         test
2      1.0         3 2017-08-12         test
1      1.0         3 2017-08-12        train
3      1.0         3 2017-08-12        train

##### Viewing and selecting data

In [65]:
df1

Break  Lunch  Dinner
2017-08-12     60     85      80
2017-08-13     60     75      85
2017-08-14     90     65      85
2017-08-15     90     80      60
2017-08-16     85     80      95
2017-08-17     85     95      85
2017-08-18     85     70      65

In [66]:
# View the top and bottom rows of a data frame:

In [67]:
df1.head()

Break  Lunch  Dinner
2017-08-12     60     85      80
2017-08-13     60     75      85
2017-08-14     90     65      85
2017-08-15     90     80      60
2017-08-16     85     80      95

In [68]:
df1.tail(3)

Break  Lunch  Dinner
2017-08-16     85     80      95
2017-08-17     85     95      85
2017-08-18     85     70      65

##### Complete list of Selection with examples:
- Selecting a single column
- Selection by label
- Selection by position

In [69]:
df1

Break  Lunch  Dinner
2017-08-12     60     85      80
2017-08-13     60     75      85
2017-08-14     90     65      85
2017-08-15     90     80      60
2017-08-16     85     80      95
2017-08-17     85     95      85
2017-08-18     85     70      65

In [74]:
# Selecting breakfast
df1[['Break','Dinner']] #dataframe

Break  Dinner
2017-08-12     60      80
2017-08-13     60      85
2017-08-14     90      85
2017-08-15     90      60
2017-08-16     85      95
2017-08-17     85      85
2017-08-18     85      65

In [75]:
df1['Break']#Series

2017-08-12    60
2017-08-13    60
2017-08-14    90
2017-08-15    90
2017-08-16    85
2017-08-17    85
2017-08-18    85
Freq: D, Name: Break, dtype: int64

In [77]:
# Selecting the first three day
df1[:3]['Break']

2017-08-12    60
2017-08-13    60
2017-08-14    90
Freq: D, Name: Break, dtype: int64

In [83]:
##### select by label ==>loc
# Selecting one assiged day
print(df1.loc['2017-08-12 '])

# Selecting two assiged days
print(df1.loc[['2017-08-12 ','2017-08-14']])

# Selecting Breakfast and Lunch in all days
print(df1.loc[:,['Break','Lunch']])

Break     60
Lunch     85
Dinner    80
Name: 2017-08-12 00:00:00, dtype: int64
            Break  Lunch  Dinner
2017-08-12     60     85      80
2017-08-14     90     65      85
            Break  Lunch
2017-08-12     60     85
2017-08-13     60     75
2017-08-14     90     65
2017-08-15     90     80
2017-08-16     85     80
2017-08-17     85     95
2017-08-18     85     70


In [86]:
#select by position ==>iloc[row,cplumns]
print(df1.iloc[3,1])
print(df1.iloc[3:5,1:3])

80
            Lunch  Dinner
2017-08-15     80      60
2017-08-16     80      95


##### How To Filter Pandas Dataframe By Values of Column?

In [ ]:
# Looking for days when the lunch bill exceeds 80
df1.lunch>80

In [ ]:
# Looking for days with two conditions


In [ ]:
# What is the following statments?

df1.iloc[2,2] = 95
df1.loc['20170818','Lunch'] = 60
df1.dinner[df1.Break>80] = 40
df1.loc['20170814','Break'] = np.nan

print(df1)


In [ ]:
# what is where
df1._____(df1>80)